### ISSUE TITLE
Vanishing optotypes as SVG

### ISSUE THREAD

**Issue by mrmorphic** [dakinlab/OpenOptotypes#1]
Hi. I'm interested in testing the vanishing optotype variations as well as the regular variants. The system I have uses SVGs for maximum rendering quality. Is it possible to have the VO variants as SVG as well. I see them in the PDF but it's not a usable format.

Cheers
M

**Comment by lhamm** [comment]
Hi, 
Thanks for your interest. The illustrator file (TheAucklandOptotypes.ai) contains vectors - do you have access this this? They are the same vectors as the regular format, but with double strokes, and they need to be displayed on a gray (gamma corrected) background.
Cheers,
Lisa

**Comment by mrmorphic** [comment]
Thanks for that. I don't have Illustrator, unfortunately. I was just hoping that you could could extract them if that was easy. Otherwise I can investigate getting illustrator or use some alternative to convert them to SVG.

**Comment by lhamm** [comment]
Ok. I've exported the vanishing opts as SVG, and pushed the change. Can you let me know if it works?

**Comment by mrmorphic** [comment]
Thanks very much, those look great! I'll be incorporating them over the next or so.

**Comment by LisaMarieHamm** [comment]
Cool, can I ask what you're using them for?

**Comment by mrmorphic** [comment]
Sure. I'm working with an optometrist John Grylls on the Kapiti Coast (who seems to know people at the uni), developing a digital eye chart system called AcuityKit. We've got a number of charts including a letter chart with an option for VO letters and background calibration, and are keen to trial the Auckland optotypes as symbols for assessing children. We met with Steven about 3 weeks ago to talk about some of the issues with it. We've actually shipped him a device so you guys can look at that too. I think we've got about 50 optometrists using it clinically at present.

**Comment by LisaMarieHamm** [comment]
Sounds really interesting - so glad they are being used! I'm glad you've had a chat with Steven about it - I'll follow up with him about the details regarding commercial use (is that the case?) and sizing/norms

**Comment by mrmorphic** [comment]
Thanks. John found it interesting working the calibration as it is quite sensitive to the particular background colour. I think we settled on something that works. With the symbol optotypes it will be interesting because everything we've done so far is 5x4 or 5x5, rather than 8.2. I think John has an idea on how to approach it, but if you have any ideas that would be appreciated (although better addressed to John, as I'm just the tech person with no optometry background)

We spoke to Steven about the commercial aspect, he seemed happy for us to use them with attribution which we're of course happy to do. At this stage we'll introduce them and see how it works in a test capacity. Because we have a system to distribute updates to devices on-site, we will be able to push these VO's to Auckland Uni as well, so you can evaluate them yourselves. I'd be keen to make sure these work as you intended them, and have some MOU on commercial use, before we push them to our wider user base, but that's all stuff that can be worked through.

**Comment by LisaMarieHamm** [comment]
Great, so it is working to display the new svgs on a grey background? The hope is that they will be  displayed on other people's devices in the end, is that correct? I'm interested to hear how you're tackling balancing them in that context. The scaling is really important too, as you note, I'd love to chat with you or John about it if that's helpful - let me know if you want to skype or anything. Again, thanks for you interest, looking forward to being in touch!

**Comment by mrmorphic** [comment]
Our model is that an optometrist uses their phone to control another screen on the wall that the patient looks at. The calibration process determines what shade of grey the optotypes are displayed on top of (given that the optotypes are transparent) on the display on the wall. The calibration display shows a panel with a checkerboard of small squares next to the displayed colour (Steven's suggestion on the checkerboard). Seems to work OK. It's probably not perfect, as monitors could have different colour temps etc, but John's feedback so far is it seems to work OK. We are generally avoiding getting into colour precision as this would require that optometrists would need colour detection equipment that I doubt many have.

It would be great to have a catch up at some point. It's probably easier than github :-) John knows Adele Jeffries, so we'll get your contact details via that channel if that's OK (rather than posting anything publically) and we can set up a call.

**Comment by LisaMarieHamm** [comment]
Sounds great!

**Comment by johngrylls** [comment]
Hi Lisa Marie,  I will contact Adele. Its been an exciting journey for us so far.
JOhn

**Comment by LisaMarieHamm** [comment]
Sounds great! (just Lisa is fine :) )
